import type { MTAEndpoints } from "./types";

const realtimeBase = "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds";

export const defaultEndpoints: MTAEndpoints = {
  subwayFeeds: {
    "1": `${realtimeBase}/nyct%2Fgtfs`,
    "2": `${realtimeBase}/nyct%2Fgtfs`,
    "3": `${realtimeBase}/nyct%2Fgtfs`,
    "4": `${realtimeBase}/nyct%2Fgtfs`,
    "5": `${realtimeBase}/nyct%2Fgtfs`,
    "6": `${realtimeBase}/nyct%2Fgtfs`,
    "7": `${realtimeBase}/nyct%2Fgtfs`,
    A: `${realtimeBase}/nyct%2Fgtfs-ace`,
    C: `${realtimeBase}/nyct%2Fgtfs-ace`,
    E: `${realtimeBase}/nyct%2Fgtfs-ace`,
    B: `${realtimeBase}/nyct%2Fgtfs-bdfm`,
    D: `${realtimeBase}/nyct%2Fgtfs-bdfm`,
    F: `${realtimeBase}/nyct%2Fgtfs-bdfm`,
    M: `${realtimeBase}/nyct%2Fgtfs-bdfm`,
    G: `${realtimeBase}/nyct%2Fgtfs-g`,
    J: `${realtimeBase}/nyct%2Fgtfs-jz`,
    Z: `${realtimeBase}/nyct%2Fgtfs-jz`,
    L: `${realtimeBase}/nyct%2Fgtfs-l`,
    N: `${realtimeBase}/nyct%2Fgtfs-nqrw`,
    Q: `${realtimeBase}/nyct%2Fgtfs-nqrw`,
    R: `${realtimeBase}/nyct%2Fgtfs-nqrw`,
    W: `${realtimeBase}/nyct%2Fgtfs-nqrw`,
    SIR: `${realtimeBase}/nyct%2Fgtfs-si`,
  },
  alerts: `${realtimeBase}/camsys%2Fall-alerts`,
  busVehicleMonitoring: "https://bustime.mta.info/api/siri/vehicle-monitoring.json",
  busStopMonitoring: "https://bustime.mta.info/api/siri/stop-monitoring.json",
};

export const subwayRouteColors: Record<string, string> = {
  "1": "EE352E",
  "2": "EE352E",
  "3": "EE352E",
  "4": "00933C",
  "5": "00933C",
  "6": "00933C",
  "7": "B933AD",
  A: "0039A6",
  C: "0039A6",
  E: "0039A6",
  B: "FF6319",
  D: "FF6319",
  F: "FF6319",
  M: "FF6319",
  G: "6CBE45",
  J: "996633",
  Z: "996633",
  L: "A7A9AC",
  N: "FCCC0A",
  Q: "FCCC0A",
  R: "FCCC0A",
  W: "FCCC0A",
  S: "808183",
  SIR: "006BB6",
};
